spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customer/**
        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**
        - id: order-line-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-line/**
        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**
        - id: category-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/category/**
        - id: payment-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**

server:
  port: 4444

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/