spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  kafka:
    bootstrap-servers: 127.0.0.1:9092
server:
    port: 8097

application:
  config:
    customer-url: http://localhost:8090/api/v1/customer
    product-url: http://localhost:8095/api/v1/product
    payment-url: http://localhost:8099/api/v1/payment

